"""Canonical SML tag to Google Slides element-type mappings."""

from __future__ import annotations


TAG_TO_TYPE = {
    # Basic shapes and non-shape page elements
    "Rect": "RECTANGLE",
    "Ellipse": "ELLIPSE",
    "RoundRect": "ROUND_RECTANGLE",
    "TextBox": "TEXT_BOX",
    "Image": "IMAGE",
    "Line": "LINE",
    "Group": "GROUP",
    "Table": "TABLE",
    "Video": "VIDEO",
    "Chart": "SHEETS_CHART",
    # Triangles and polygons
    "Triangle": "TRIANGLE",
    "RightTriangle": "RIGHT_TRIANGLE",
    "Parallelogram": "PARALLELOGRAM",
    "Trapezoid": "TRAPEZOID",
    "Pentagon": "PENTAGON",
    "Hexagon": "HEXAGON",
    "Heptagon": "HEPTAGON",
    "Octagon": "OCTAGON",
    "Decagon": "DECAGON",
    "Dodecagon": "DODECAGON",
    # Stars
    "Star4": "STAR_4",
    "Star5": "STAR_5",
    "Star6": "STAR_6",
    "Star8": "STAR_8",
    "Star10": "STAR_10",
    "Star12": "STAR_12",
    "Star16": "STAR_16",
    "Star24": "STAR_24",
    "Star32": "STAR_32",
    # Other shapes
    "Diamond": "DIAMOND",
    "Chevron": "CHEVRON",
    "HomePlate": "HOME_PLATE",
    "Plus": "PLUS",
    "Donut": "DONUT",
    "Pie": "PIE",
    "Arc": "ARC",
    "Chord": "CHORD",
    "BlockArc": "BLOCK_ARC",
    "Frame": "FRAME",
    "HalfFrame": "HALF_FRAME",
    "Corner": "CORNER",
    "DiagonalStripe": "DIAGONAL_STRIPE",
    "LShape": "L_SHAPE",
    "Can": "CAN",
    "Cube": "CUBE",
    "Bevel": "BEVEL",
    "FoldedCorner": "FOLDED_CORNER",
    "SmileyFace": "SMILEY_FACE",
    "Heart": "HEART",
    "LightningBolt": "LIGHTNING_BOLT",
    "Sun": "SUN",
    "Moon": "MOON",
    "Cloud": "CLOUD",
    "Plaque": "PLAQUE",
    # Arrows
    "Arrow": "ARROW",
    "ArrowLeft": "LEFT_ARROW",
    "ArrowRight": "RIGHT_ARROW",
    "ArrowUp": "UP_ARROW",
    "ArrowDown": "DOWN_ARROW",
    "ArrowLeftRight": "LEFT_RIGHT_ARROW",
    "ArrowUpDown": "UP_DOWN_ARROW",
    "ArrowQuad": "QUAD_ARROW",
    "ArrowLeftRightUp": "LEFT_RIGHT_UP_ARROW",
    "ArrowBent": "BENT_ARROW",
    "ArrowUTurn": "U_TURN_ARROW",
    "ArrowCurvedLeft": "CURVED_LEFT_ARROW",
    "ArrowCurvedRight": "CURVED_RIGHT_ARROW",
    "ArrowCurvedUp": "CURVED_UP_ARROW",
    "ArrowCurvedDown": "CURVED_DOWN_ARROW",
    "ArrowStripedRight": "STRIPED_RIGHT_ARROW",
    "ArrowNotchedRight": "NOTCHED_RIGHT_ARROW",
    "ArrowPentagon": "PENTAGON_ARROW",
    "ArrowChevron": "CHEVRON_ARROW",
    "ArrowCircular": "CIRCULAR_ARROW",
    # Callouts
    "CalloutRect": "WEDGE_RECTANGLE_CALLOUT",
    "CalloutRoundRect": "WEDGE_ROUND_RECTANGLE_CALLOUT",
    "CalloutEllipse": "WEDGE_ELLIPSE_CALLOUT",
    "CalloutCloud": "CLOUD_CALLOUT",
    # Flowchart shapes
    "FlowProcess": "FLOW_CHART_PROCESS",
    "FlowDecision": "FLOW_CHART_DECISION",
    "FlowInputOutput": "FLOW_CHART_INPUT_OUTPUT",
    "FlowPredefinedProcess": "FLOW_CHART_PREDEFINED_PROCESS",
    "FlowInternalStorage": "FLOW_CHART_INTERNAL_STORAGE",
    "FlowDocument": "FLOW_CHART_DOCUMENT",
    "FlowMultidocument": "FLOW_CHART_MULTIDOCUMENT",
    "FlowTerminator": "FLOW_CHART_TERMINATOR",
    "FlowPreparation": "FLOW_CHART_PREPARATION",
    "FlowManualInput": "FLOW_CHART_MANUAL_INPUT",
    "FlowManualOperation": "FLOW_CHART_MANUAL_OPERATION",
    "FlowConnector": "FLOW_CHART_CONNECTOR",
    "FlowPunchedCard": "FLOW_CHART_PUNCHED_CARD",
    "FlowPunchedTape": "FLOW_CHART_PUNCHED_TAPE",
    "FlowSummingJunction": "FLOW_CHART_SUMMING_JUNCTION",
    "FlowOr": "FLOW_CHART_OR",
    "FlowCollate": "FLOW_CHART_COLLATE",
    "FlowSort": "FLOW_CHART_SORT",
    "FlowExtract": "FLOW_CHART_EXTRACT",
    "FlowMerge": "FLOW_CHART_MERGE",
    "FlowOnlineStorage": "FLOW_CHART_ONLINE_STORAGE",
    "FlowMagneticTape": "FLOW_CHART_MAGNETIC_TAPE",
    "FlowMagneticDisk": "FLOW_CHART_MAGNETIC_DISK",
    "FlowMagneticDrum": "FLOW_CHART_MAGNETIC_DRUM",
    "FlowDisplay": "FLOW_CHART_DISPLAY",
    "FlowDelay": "FLOW_CHART_DELAY",
    "FlowAlternateProcess": "FLOW_CHART_ALTERNATE_PROCESS",
    "FlowOffpageConnector": "FLOW_CHART_OFFPAGE_CONNECTOR",
    "FlowData": "FLOW_CHART_DATA",
    # Equation shapes
    "MathPlus": "MATH_PLUS",
    "MathMinus": "MATH_MINUS",
    "MathMultiply": "MATH_MULTIPLY",
    "MathDivide": "MATH_DIVIDE",
    "MathEqual": "MATH_EQUAL",
    "MathNotEqual": "MATH_NOT_EQUAL",
    # Brackets, ribbons, and rounded rectangle variants
    "BracketLeft": "LEFT_BRACKET",
    "BracketRight": "RIGHT_BRACKET",
    "BraceLeft": "LEFT_BRACE",
    "BraceRight": "RIGHT_BRACE",
    "BracketPair": "BRACKET_PAIR",
    "BracePair": "BRACE_PAIR",
    "Ribbon": "RIBBON",
    "Ribbon2": "RIBBON_2",
    "SnipRoundRect": "SNIP_ROUND_RECTANGLE",
    "Snip2SameRect": "SNIP_2_SAME_RECTANGLE",
    "Snip2DiagRect": "SNIP_2_DIAGONAL_RECTANGLE",
    "Round1Rect": "ROUND_1_RECTANGLE",
    "Round2SameRect": "ROUND_2_SAME_RECTANGLE",
    "Round2DiagRect": "ROUND_2_DIAGONAL_RECTANGLE",
    # Custom/unknown API shape variants that still round-trip as shapes
    "Custom": "CUSTOM",
    "Shape": "SHAPE",
}

TYPE_TO_TAG = {element_type: tag for tag, element_type in TAG_TO_TYPE.items()}

_NON_SHAPE_TYPES = {"IMAGE", "LINE", "GROUP", "TABLE", "VIDEO", "SHEETS_CHART"}
VALID_GOOGLE_TYPES = frozenset(TAG_TO_TYPE.values()) - _NON_SHAPE_TYPES
